"""
Precomputes a coarse visual fingerprint for a handful of reference photos
per landmark, using the exact same algorithm the browser will run on live
camera frames (js/localization.js): resize to 8x8, average RGB per cell,
normalize 0..1, flatten to a 192-length vector.

This is NOT a deep embedding (no neural net) — it's a classical low-res
color/layout descriptor, sometimes called a "tiny image" or block-color
fingerprint. It's cheap enough to run on any phone with zero model
download, but it only distinguishes scenes that look quite different in
overall color and layout (lift doors vs. a sofa vs. a stairwell) — it will
NOT reliably tell two similar-looking corridor segments apart. That
trade-off is documented in localization.js and the README.

Run once at build time; output is committed as js/venues/*.fingerprints.js
so the browser never has to touch Python or the raw dataset.
"""
import json
from pathlib import Path
from PIL import Image

GRID = 8
PROJECT_ROOT = Path(__file__).parent.parent
DATASET_ROOT = PROJECT_ROOT / "dataset"

def fingerprint(path):
    img = Image.open(path).convert("RGB")
    # Center-crop to square first so aspect ratio doesn't skew the grid,
    # matching what the runtime does with the camera frame.
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side)).resize((GRID, GRID), Image.BILINEAR)
    pixels = list(img.getdata())
    vec = []
    for (r, g, b) in pixels:
        vec.extend([r / 255.0, g / 255.0, b / 255.0])
    return vec

# venueId -> nodeId -> [reference photo filenames within dataset/<venueId>/]
REFERENCES = {
    "sjt7": {
        "stairs": ["WhatsApp Image 2026-09-07 at 9.52.15 PM.jpeg"],
        "room_711_712": ["WhatsApp Image 2026-09-07 at 9.50.14 PM.jpeg"],
        "water_cooler": ["WhatsApp Image 2026-09-07 at 9.50.16 PM.jpeg"],
        "open_corridor": ["WhatsApp Image 2026-09-07 at 9.52.27 PM.jpeg"],
        # No distinct-enough reference photo available for: lobby, faculty_cabins,
        # washroom_women (shares a frame with water_cooler — too ambiguous to
        # trust), room_715, corridor_end. These are simply left out of the
        # fingerprint database below; localization will never guess them, and
        # the app falls back to asking the user directly. Add more reference
        # photos here and re-run this script to improve coverage.
    },
    "hblock3": {
        "lift": [
            "WhatsApp Image 2026-09-07 at 11.04.41 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.43 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.46 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.47 PM.jpeg",
        ],
        "stairs": ["WhatsApp Image 2026-09-07 at 11.04.40 PM.jpeg"],
        "water_cooler": [
            "WhatsApp Image 2026-09-07 at 11.04.44 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.45 PM.jpeg",
        ],
        "common_room": [
            "WhatsApp Image 2026-09-07 at 11.04.07 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.08 PM.jpeg",
        ],
        "storage_pantry": [
            "WhatsApp Image 2026-09-07 at 11.04.10 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.25 PM.jpeg",
        ],
        "balcony": ["WhatsApp Image 2026-09-07 at 11.04.26 PM.jpeg"],
        "dormitory_rooms": [
            "WhatsApp Image 2026-09-07 at 11.04.27 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.28 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.30 PM.jpeg",
        ],
        "corridor_start": [
            "WhatsApp Image 2026-09-07 at 11.04.49 PM.jpeg",
            "WhatsApp Image 2026-09-07 at 11.04.51 PM.jpeg",
        ],
        "corridor_junction": ["WhatsApp Image 2026-09-07 at 11.04.38 PM.jpeg"],
        # No distinct reference available for: washroom (only ever seen in
        # frame together with the water cooler, not distinguishable from it
        # with this technique) — left out rather than shipping a misleading
        # guess.
    },
}

DATASET_DIR_NAME = {"sjt7": "sjt-7th-floor", "hblock3": "hblock-3rd-floor"}

for venue_id, nodes in REFERENCES.items():
    out = {}
    folder = DATASET_ROOT / DATASET_DIR_NAME[venue_id]
    for node_id, filenames in nodes.items():
        vectors = []
        for fn in filenames:
            p = folder / fn
            if not p.exists():
                print(f"WARNING missing {p}")
                continue
            vectors.append([round(x, 4) for x in fingerprint(p)])
        out[node_id] = vectors

    js_path = PROJECT_ROOT / "js" / "venues" / f"{DATASET_DIR_NAME[venue_id]}.fingerprints.js"
    js_path.write_text(
        "// Auto-generated by scripts/precompute_fingerprints.py — do not hand-edit.\n"
        "// Coarse 8x8 color-grid visual fingerprints for landmark recognition.\n"
        "// See localization.js for the matching algorithm and its limits.\n"
        f"window.registerFingerprints('{venue_id}', {json.dumps(out)});\n"
    )
    total_vecs = sum(len(v) for v in out.values())
    print(f"{venue_id}: {len(out)} nodes, {total_vecs} reference vectors -> {js_path}")
